### PR TITLE
Benchmark fix

### PR DESCRIPTION
**Pull request by cryptisk-grs**
Lets the benchmarks run again with latest benchmarkdotnet on .NET 5. Haven't updated the versions of the other projects we're testing against, but I want to write a bunch of different benchmarks to see performance per type before I go and do that work.

### CODE REVIEW

**Comment by maurosampietro** [comment]
Instead of fixing readme and perf benchamark and other shit, try and read the issues: this library have many problems and in facts does not work at all in many scenarios.

**Comment by tcsaddul** [comment]
@maurosampietro These open source developers have shared their talents for FREE to help other developers.  The "other" developers don't have the right to demand anything from them except at least to make a "request".

**Comment by maurosampietro** [comment]
If you don’t have the will to maintain a piece of open source software anymore transfer the ownership of the project.

**Comment by cryptisk-grs** [comment]
> Instead of fixing readme and perf benchamark and other shit, try and read the issues: this library have many problems and in facts does not work at all in many scenarios :)

The merge request selected neuecc's repo instead of my forked repo. This happened in error and was closed immediately. If you want a working branch, check that one out, we already have new nuget packages working in production by myself and the project's users.

**Pull request closed without merging**
